schema_version: 1

context:
  version: 1.0.21

package:
  name: libsodium
  version: ${{ version }}

source:
  # stable tarball gets patches and hash will change.
  # If we want reproducible URLs, we can use
  # commits on the stable branch, which won't get autotick PRs
  url: https://download.libsodium.org/libsodium/releases/libsodium-${{ version }}-stable.tar.gz
  sha256: 2c7c0083a3d4151634b4237139a6bc216ae3c5cd95ad9c04fc16551021e28a0b

build:
  number: 1
  script: build

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - libtool
        - make
  run_exports:
    - ${{ pin_subpackage("libsodium", upper_bound="x.x.x") }}

tests:
  - package_contents:
      lib:
        - if: unix
          then: sodium
        - if: win
          then: libsodium
      include:
        - sodium.h
        - sodium/version.h
      files:
        not_exists: 
          - if: unix
            then:
              - lib/libsodium.a
          - if: win
            then:
              - Library/lib/libsodium_static.lib


about:
  license: ISC
  license_file: LICENSE
  summary: A modern and easy-to-use crypto library
  description: |
    Sodium is a new, easy-to-use software library for encryption, decryption,
    signatures, password hashing and more. It is a portable, cross-compilable,
    installable, packageable fork of NaCl, with a compatible API, and an
    extended API to improve usability even further. Its goal is to provide all
    of the core operations needed to build higher-level cryptographic tools.
  homepage: https://libsodium.org
  repository: https://github.com/jedisct1/libsodium
  documentation: https://download.libsodium.org/doc

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
