schema_version: 1

context:
  version: 1.0.21

package:
  name: libsodium
  version: ${{ version }}

source:
  url: https://download.libsodium.org/libsodium/releases/libsodium-${{ version }}.tar.gz
  sha256: 9e4285c7a419e82dedb0be63a72eea357d6943bc3e28e6735bf600dd4883feaf
  patches:
    # to regen stable branch patch list, see stable-patches/README.md
    - stable-patches/0001-Fix-compilation-with-GCC-on-aarch64.patch
    - stable-patches/0002-Update-ChangeLog.patch
    - stable-patches/0003-CI-compile-using-GCC-on-aarch64.patch
    - stable-patches/0004-Brad-Barden-IAMB-wrote-bindings-for-Perl.patch
    - stable-patches/0005-Export-missing-crypto_ipcrypt_nd_keygen-helper-funct.patch
    - stable-patches/0006-Update-ChangeLog.patch
    - stable-patches/0007-Windows-Server-2019-has-been-retired-from-Azure-Pipe.patch
    - stable-patches/0008-Try-installing-VS2019-manually.patch
    - stable-patches/0009-build.zig-fix-using-as-a-dependency-in-other-project.patch
    - stable-patches/0010-Update-ChangeLog.patch
    - stable-patches/0011-Add-ARM-acceleration-for-SHA3.patch
    - stable-patches/0012-CI-test-more-aarch64-gcc-combinations.patch
    - stable-patches/0013-Update-ChangeLog.patch
    - stable-patches/0014-Bump-max-memory-of-JavaScript-Sumo-builds-to-80-MiB.patch
    - stable-patches/0015-Compatibility-with-gcc-4.x.patch
    - stable-patches/0016-Emscripten-remove-LTO.patch
    - stable-patches/0017-randombytes-cleanup-the-JavaScript-path.patch
    - stable-patches/0018-Document-the-LTO-change.patch
    - stable-patches/0019-Emscripten-add-an-option-to-compile-with-SIMD.patch
    - stable-patches/0020-Add-WASM-SIMD-implementations-of-Argon2.patch
    - stable-patches/0021-VS-2026-toolsets-may-not-define-PlatformToolsetVersi.patch
    - stable-patches/0022-Update-ChangeLog.patch
    - stable-patches/0023-secretbox-zero-the-state-after-checking-only-the-tag.patch
    - stable-patches/0024-Zero-the-state-afetr-AES-decryption.patch
    - stable-patches/0025-Update-ChangeLog.patch
    - stable-patches/0026-emscripten-build-native-ESM-module.patch

build:
  number: 3
  script: build

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - libtool
        - make
  run_exports:
    - ${{ pin_subpackage("libsodium", upper_bound="x.x.x") }}

tests:
  - package_contents:
      lib:
        - if: unix
          then: sodium
        - if: win
          then: libsodium
      include:
        - sodium.h
        - sodium/version.h
      files:
        not_exists: 
          - if: unix
            then:
              - lib/libsodium.a
          - if: win
            then:
              - Library/lib/libsodium_static.lib
  - script:
      - if: unix
        then:
          - cmake -S test -B test/build $CMAKE_ARGS
        else:
          - cmake -S test -B test/build %CMAKE_ARGS%
      - cmake --build test/build
      - ctest --test-dir test/build --output-on-failure
    files:
      recipe:
        - test/
    requirements:
      run:
        - cmake
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - if: unix
          then:
            - make

about:
  license: ISC
  license_file: LICENSE
  summary: A modern and easy-to-use crypto library
  description: |
    Sodium is a new, easy-to-use software library for encryption, decryption,
    signatures, password hashing and more. It is a portable, cross-compilable,
    installable, packageable fork of NaCl, with a compatible API, and an
    extended API to improve usability even further. Its goal is to provide all
    of the core operations needed to build higher-level cryptographic tools.
  homepage: https://libsodium.org
  repository: https://github.com/jedisct1/libsodium
  documentation: https://download.libsodium.org/doc

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
