schema_version: 1

context:
  version: 1.0.21

package:
  name: libsodium
  version: ${{ version }}

source:
  url: https://download.libsodium.org/libsodium/releases/libsodium-${{ version }}.tar.gz
  sha256: 9e4285c7a419e82dedb0be63a72eea357d6943bc3e28e6735bf600dd4883feaf
  patches:
    # FIXME: arm patch applied upstream, remove after 1.0.22
    - 6702f69bef6044163acc7715e6ac7e430890ce78.patch

build:
  number: 0
  script: build

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - libtool
        - make
  run_exports:
    - ${{ pin_subpackage("libsodium", upper_bound="x.x.x") }}

tests:
  - package_contents:
      lib:
        - sodium
      include:
        - sodium.h
        - if: win
          then:
            - sodium/version.h
      files:
        not_exists: 
          - if: unix
            then:
              - lib/libsodium.a
          - if: win
            then:
              - "%LIBRARY_LIB%/libsodium_static.lib"
  - script:
      - if: unix
        then: test ! -f ${PREFIX}/lib/libsodium.a
      - if: osx
        then: test -f ${PREFIX}/lib/libsodium.dylib
      - if: linux
        then: test -f ${PREFIX}/lib/libsodium.so
      - if: win
        then: if not exist %LIBRARY_INC%\sodium.h              exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\sodium\version.h      exit 1
      - if: win
        then: if not exist %LIBRARY_BIN%\libsodium.dll         exit 1
      - if: win
        then: if not exist %LIBRARY_LIB%\libsodium.lib         exit 1
      - if: win
        then: if exist %LIBRARY_LIB%\libsodium_static.lib  exit 1

about:
  license: ISC
  license_file: LICENSE
  summary: A modern and easy-to-use crypto library
  description: |
    Sodium is a new, easy-to-use software library for encryption, decryption,
    signatures, password hashing and more. It is a portable, cross-compilable,
    installable, packageable fork of NaCl, with a compatible API, and an
    extended API to improve usability even further. Its goal is to provide all
    of the core operations needed to build higher-level cryptographic tools.
  homepage: https://libsodium.org
  repository: https://github.com/jedisct1/libsodium
  documentation: https://download.libsodium.org/doc

extra:
  recipe-maintainers:
    - jakirkham
    - minrk

